### ISSUE TITLE
Add Context for Subscriptions

### ISSUE THREAD

**Issue by MoonTahoe** [howtographql/graphql-js#10]
When you try to create a nested query in the `Link` subscription, the response is `[Object object]`. I opened an issue at apollographql/subscriptions-transport-ws#306, and we found out that this issue occures because mongo and the dataloaders are missing from the subscription context.

```graphql
subscription {
  Link(filter:{
    mutation_in: [CREATED]
  }) {
    mutation
    node {
      id
      url
      description
      postedBy {
          name
      }
    }
  }
}
```

The solution:

```javascript
    SubscriptionServer.create(
            {
               execute, 
               subscribe, 
               schema,
               onOperation: (message, params, webSocket) => 
                   Object.assign(
                      params, 
                      {
                          context: {
                              mongo, 
                              dataloaders: buildDataloaders(mongo)
                          }
                      })
            },
            { server, path: '/subscriptions' },
      );
```

**Comment by AliceSum** [comment]
what?

**Comment by MoonTahoe** [comment]
Mongo collections need to be added to context for subscriptions too or the resolvers have access to them for subscriptions.

But it looks like this lesson has been replaced with ‘graphql-yoga’?

**Comment by JonathanSum** [comment]
I do not know. I only know the subscription does not work on both backend nodeJS tutorial and front end Reactjs with Apollo client tutorial, and many people have posted the same thing in the issue section.
