### ISSUE TITLE
Missing @unique

### ISSUE THREAD

**Issue by rauleite** [howtographql/graphql-js#12]
I think this line is missing.
`id: ID! @unique`
Such as: [datamodel.graphql](https://github.com/howtographql/graphql-js/blob/master/database/datamodel.graphql#L2)
On: **Adding a vote mutation** 
[5-applying-authentication](https://www.howtographql.com/graphql-js/5-applying-authentication/
)
It does not work without it.

**Comment by rauleite** [comment]
And so, creating a server by: 
`graphql create server --boilerplate node-basic`
the imports should be:
`# import ... from "./generated/prisma.graphql"`
and not ending with:
`"./generated/database.graphql"`.

This causes a strange error for Newbies (like me haha)

**Comment by AliceSum** [comment]
if your problem is solved, plz close it by yourself. (I am a Newbies who has done a lot of stupid error and posted here too :D

**Comment by marktani** [comment]
I am not quite sure what the actual error is, can you describe your problem in more detail, or provide a PR with a fix @rauleite? 🙂

**Comment by rauleite** [comment]
I just saw that you apparently fixed it, about my first post.
I do not know about the second, but I'm closing it.
