### ISSUE TITLE
requestAnimationFrame eating up CPU

### ISSUE THREAD

**Issue by jsnelgro** [howtographql/graphql-js#13]
Just wanted to let you know there's an animation or something in your tutorial (which is excellent btw!) that's causing my CPU to kick into overdrive. Opening the dev console and adding `window.requestAnimationFrame = () => {}` seems to fix the issue.

**Comment by AliceSum** [comment]
which tutorial?

**Comment by jsnelgro** [comment]
@JonathanSum all of them, I believe. I did the javascript tutorial: https://www.howtographql.com/graphql-js/1-getting-started/

I think it might be the confetti animation at the end?

**Comment by nikolasburk** [comment]
Issue moved to [howtographql/howtographql #506](https://github.com/howtographql/howtographql/issues/506) via [**ZenHub**](https://www.zenhub.com/)
