### ISSUE TITLE
Confusion at the end of 'Applying Authentication' chapter.

### ISSUE THREAD

**Issue by jsrhodes15** [howtographql/graphql-js#21]
I have been following along the graphql-js tutorial, and when I got to the end of 'Applying authentication' chapter, I hit a snag:

I got to the code example for the 'vote' mutation, and when finished, the tutorial explains what is happening. It then goes on to instruct the user to restart the server and send a 'vote' mutation in the app playground. This didn't work for me. I spent quite some time, and actually had to leave and come back (to clear my head) a total of 3 times. 

<img width="737" alt="screen shot 2018-03-23 at 12 15 53 p
m" src="https://user-images.githubusercontent.com/13190339/37859711-53c0b5fc-2eee-11e8-88ff-1bf1cac6b4fb.png">

I am embarrassed to even write this, having been a 'professional' JS developer for almost 2 years now, but I never exported 'vote'. There is no hint or reminder, and it is not shown in the code. I ended up coming to this github and comparing the source code to mine, which is how I found the discrepancy.

As someone who 'knows' their JS, I consider this user error on my part, but I can certainly see this affecting greener devs, especially since I know I was so concerned with understanding the graphql part that I overlooked something as 'basic' as exporting my methods.

Anyway, just wanted to point that out, and would also like to offer up that I would be happy to submit a PR myself if this is deemed an actual bug.

Thanks for the hard work and overall great tutorials!

**Comment by nikolasburk** [comment]
Hey @jsrhodes15, thanks so much for the feedback - it is super helpful!

One of the qualities of How to GraphQL is supposed to be that it walks the reader through _every_ step that they should perform. So I apologize for your frustrating experience, I'll fix this soon. Otherwise - PRs are definitely always welcome as well :)

**Comment by nikolasburk** [comment]
Just added the step to the tutorial, thanks a again for opening this issue 🙏
