### ISSUE TITLE
ERROR -> "Cannot read property 'get' of undefined" when using post with auth headers

### ISSUE THREAD

**Issue by mmswi** [howtographql/graphql-js#24]
Hello all,

Any ideas why I'm getting this error?

My utils file here: https://github.com/mmswi/graphQL-tut/blob/master/src/utils.js
My mutation here: https://github.com/mmswi/graphQL-tut/blob/master/src/resolvers/Mutation.js
Note, I've hardcoded the user id and used a try catch block, as I got an error in the console that was saying:
`(node:16656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

Anyways, same "Cannot read property 'get' of undefined" error received when not using a try catch block. 

With the hardcoded id, the post function works, so I'm wondering why is the context get returning that error. The auth headers have been added also in the graphql playground
`{
  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamd5ODg1MXczZGd3MGIwOG91dHE1OWRrIiwiaWF0IjoxNTI1ODkyMjQwfQ.mW-uDhlG3cGJRi14lw2g_YQSVLWS1Xnkw_VzK_QliO0"
}`

Thanks

**Comment by sapkra** [comment]
I'm getting the same error with subscriptions. Have you found a fix for it?

**Comment by mmswi** [comment]
Unfortunately, no. But also, I don't use graphql in my job or projects.

**Comment by sapkra** [comment]
Ok but thanks for you quick answer.

**Comment by itscarlosrufo** [comment]
Thanks @mmswi for opening this issue 😄. It seems to be solved following the latest docs. Closing this for now, please, feel free to open an issue if you cannot make it work!

**Comment by starcraft0429** [comment]
I am following document now but it give me same error.
I think it is not fixed yet?
```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot read property 'get' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "post"
      ]
    }
  ]
}
```

**Comment by brittneypostma** [comment]
Having the same issue going through the How To GraphQL backend graphql-node tutorial. Here is the repo [hackernews-node](https://github.com/brittneypostma/hackernews-node). Getting error Cannot read property 'get' of undefined from the src/utils.js file.

**Comment by sdhmdh** [comment]
Hi @brittneypostma , did you get the solution?

**Comment by ISProjectsIoTCR** [comment]
Mismo error, alguna solución? Estoy usando strapi v4 y al hacer una mutation aparece: Error: GraphQL error: Cannot read property 'get' of undefined
GraphQL error: Cannot read property 'get' of undefined


Ayuda por favor
