### ISSUE TITLE
subscription with react js   don't know how to use subscription with react js  to make like in lyrics and update in other screens

### ISSUE THREAD

**Issue by alaamahersalem** [howtographql/graphql-js#26]
const graphql = require('graphql');
const { GraphQLObjectType, GraphQLList, GraphQLNonNull, GraphQLID } = graphql;
const mongoose = require('mongoose');
const Lyric = mongoose.model('lyric');
const LyricType = require('./lyric_type');

const { PubSub, withFilter } = require('graphql-subscriptions');

const pubsub = new PubSub();

const SubscriptionQuery = new GraphQLObjectType({
	name: 'Subscription',
	fields: {
		addLike: {
			type: LyricType,
			args: { id: { type: GraphQLID } },
			resolve(parentValue, { id }) {
				const AddLike = Lyric.like(id);
				if (!AddLike) throw new Error('lyric does not exist');
				pubsub.publish('LikeAdded', { LikeAdded: addLike, id: AddLike.id });
				return AddLike;
			},
			LikeAdded: {
				subscribe: withFilter(
					() => pubsub.asyncIterator('LikeAdded'),
					(payload, variables) => {
						const ly = Lyric.findById(variables.id);
						return ly;
					}
				),
			},
		},
	},
});

module.exports = SubscriptionQuery;

**Comment by nikolasburk** [comment]
Hey @alaamahersalem, it seems like yout issue is not related to this repository so I'm closing it. Feel free to open issues with questions about this specific project in the future 🙌
