### ISSUE TITLE
[Question] how do you suggest creating the same subscription with graphql-js?

### ISSUE THREAD

**Issue by eladams** [howtographql/graphql-js#3]

**Comment by nikolasburk** [comment]
Hi @eladams! My sincere apologies for the delay of responding to your issue - unfortunately I wasn't able to put in much maintenance effort into How To GraphQL over the past months. However, I have just started a major cleanup and am taking a look at all issues.

As the `graphql-js` tutorial has been updated recently, it seems your question might be out of date. Please let me know if you have any other questions and I'll get back ASAP 🙂
