### ISSUE TITLE
Error: 'prisma.yml should NOT have additional properties. additionalProperty: hooks'

### ISSUE THREAD

**Issue by alexpi** [howtographql/graphql-js#32]
Hello,

I am on the 'Connecting Server and Database with Prisma Bindings' tutorial, and near the end of the page after adding the hooks property and running 'prisma deploy', I am getting the error:
```
!  Invalid prisma.yml file
!  prisma.yml should NOT have additional properties. additionalProperty: hooks
```

I am using prisma@1.6.3 as instructed.

**Comment by tylerama** [comment]
@alexpi were you able to resolve this error? Looking for a fix as well

**Comment by alexpi** [comment]
@tylerama I updated prisma to the latest version, and it worked fine. Maybe the tutorial was updated?

**Comment by itscarlosrufo** [comment]
Thanks @alexpi for opening this issue 😄. As you've mentioned, it was updated and now is working!
