### ISSUE TITLE
Defining secret for prisma-binding

### ISSUE THREAD

**Issue by craigblunden** [howtographql/graphql-js#34]
I'm new to Prisma and graph QL so apologies if this comes down to lack of knowledge.

According to the guide, the secret isn't defined when you initiate db within the context of the GraphQL Server.

https://www.howtographql.com/graphql-js/5-connecting-server-and-database/

I've been getting authentication errors on my application requests within the playground for hours until I looked through the actual package to find out its a required field:

https://github.com/prismagraphql/prisma-binding

Statically defining the secret resolved the issue.

PR #35

**Comment by nikolasburk** [comment]
Again, thanks so much @craigblunden 🙏
