### ISSUE TITLE
Unable to signup, invalid token, unable to authenticate

### ISSUE THREAD

**Issue by thibauds** [howtographql/graphql-js#36]
I'm trying to signup using the playground, but I'm unable to do it because I get an "invalid token error".

Here are the steps to reproduce:
```
git clone https://github.com/howtographql/graphql-js
cd graphql-js
yarn install
cd database
vim prisma.yml
# comment the first line (endpoint:...)
cd ..
prisma deploy
# > Demo server
# > prisma-eu1
# > database
# > dev

# endpoint is now set in the file database/prisma.yml
# copy this value, and replace the endpoint value in src/index.js

prisma token
# copy this value as the Bearer token for the Authorization Header
yarn dev
```
Then when I execute the following query in the playground on the database/dev with the previously generated token
```
{ links { id } }
```
It's working as expected.

Nevertheless when selecting the app/default project in the playground and executing the following query
```
mutation {
  signup(
    name: "myName"
    email: "my@email.com"
    password: "mystrongpassword"
  ) {
    token
    user {
      id
    }
  }
}
```
I got the following error
```
{
  "data": {
    "signup": null
  },
  "errors": [
    {
      "message": "Your token is invalid. It might have expired or you might be using a token from a different project.",
      "locations": [],
      "path": [
        "createUser"
      ],
      "code": 3015,
      "requestId": "eu1:api:cjjckt..."
    }
  ]
}
```
I tried with and without the previoulsy generated token and got the same error.

I'm confused. As far as I understand, the prisma layer needs a token to execute the signup mutation, it makes sense otherwise the prisma layer would be open to anyone and we only want our app (or authenticated users) to be able to execute query on our prisma layer. Nevertheless I don't see anything in this repo, in the application layer that would authenticate to the prisma layer.
After logging in I could use the token from the user and pass it to the prisma layer but for the signup I don't have any token.
Am I missing something? Is it left to the developer because it is specific to the way we want our application layer to communicate with our prisma layer?

prisma version:
`prisma/1.11.0 (linux-x64) node-v10.4.0`

**Comment by thibauds** [comment]
Thanks to this issue #34 (thanks @craigblunden) 
I'm using the same secret as the prisma layer so I can use the token generated with prisma.

**Comment by BrentFarese** [comment]
Had the same issue as above and @thibauds solved it.  Hard coded in the secret into the server config:

```const server = new GraphQLServer({
    typeDefs: './src/schema.graphql',
    resolvers,
    context: req => ({
        ...req,
        db: new Prisma({
            typeDefs: 'src/generated/prisma.graphql',
            endpoint: YOUR_ENDPOINT,
            secret: 'mysecret123',
            debug: true,
        }),
    }),
});

**Comment by itscarlosrufo** [comment]
Thanks @thibauds for opening this issue 😄. It seems to be solved following the latest docs. Closing this for now, please, feel free to open an issue if you cannot make it work!
