### ISSUE TITLE
Deadlink - graphql-bindings

### ISSUE THREAD

**Issue by bduron** [howtographql/graphql-js#38]
Hi, the link to `graphql-bindings` on https://www.howtographql.com/graphql-js/0-introduction/ is dead

Current => https://blog.graph.cool/reusing-composing-graphql-apis-with-graphql-bindings-80a4aa37cff5

Working link => https://www.prisma.io/blog/reusing-and-composing-graphql-apis-with-graphql-bindings-80a4aa37cff5/

Thank you for the tutorial!

**Comment by victorhmp** [comment]
I've just sent a PR to the howtographql repository, which contains the actual text content for the https://www.howtographql.com/graphql-js/0-introduction/ page, that updates the link :)

**Comment by itscarlosrufo** [comment]
Thanks @bduron @victorhmp for opening this issue 😄. It seems solved. Closing this for now, please, feel free to open an issue if it still doesn't work!

**Comment by jorgecolonconsulting** [comment]
This page doesn't exist anymore so here's the link on the wayback machine: https://web.archive.org/web/20180724172011/https://www.prisma.io/blog/reusing-and-composing-graphql-apis-with-graphql-bindings-80a4aa37cff5/
