### ISSUE TITLE
Subscription error with the latest version of prisma-binding package

### ISSUE THREAD

**Issue by mrkvon** [howtographql/graphql-js#42]
When I upgrade `prisma-binding` from `^2.0.2` to `^2.1.4`

newLink (and newVote) subscriptions fail with
```
{
  "error": {
    "name": "TypeError",
    "message": "Cannot read property 'link' of undefined"
  }
}
```

This error happens when I follow the tutorial today. It is not an issue with the repository itself, but with the [related tutorial](https://www.howtographql.com/graphql-js/7-subscriptions/) which seems to not reflect some recent breaking changes between minor versions of `prisma-binding`

## reproduce
1. install this repository, `yarn dev`, go to playground, sign up, provide authorization header
2. test that newLink subscription works
3. 
    ``` bash 
    yarn add graphql-yoga@latest
    yarn add prisma-binding@latest
    ```
4. restart with `yarn dev`
4. test newLink subscription again and observe the error

**Comment by mrkvon** [comment]
Related: https://github.com/prisma/prisma-binding/issues/229
Related: https://github.com/howtographql/howtographql/issues/758

**Comment by mrimran** [comment]
I was getting the same issue and by closely analyzing I came to know that I'm making a typo here

`return context.db.subscription.link`, the typo was `subscribtion` :) The issue no more comes on my end.

**Comment by mrkvon** [comment]
With `prisma-binding^2.1.6` everything works as expected again. Either upgrading the package or generating binding code again may have helped.
Closing.
