### ISSUE TITLE
Explanation for aggregate in the tutorial

### ISSUE THREAD

**Issue by RecoX** [howtographql/graphql-js#50]
https://github.com/howtographql/graphql-js/blob/d07c2c5aa854bdcd487276e803986859cc1e9c26/src/resolvers/Query.js#L11

What does aggregate? in the tutorial is not mentioned
https://www.howtographql.com/graphql-js/8-filtering-pagination-and-sorting/

**Comment by itscarlosrufo** [comment]
Thanks @RecoX for opening this issue 😄, I guess, in order to keep the tutorial simplicity it wasn't included, closing this as it'd probably be updated!
