### ISSUE TITLE
Idea for dynamic models with validation

### ISSUE THREAD

**Issue by tabvn** [howtographql/graphql-js#6]
ex:
user.json
{
peroperties:{
  "_id":{ "type": ID, "unique": true},
  "firstName":{ "type": String},
  "lastName":{ "type": String},
  "email":{ "type": String, "unique": true, "index": true},
}
}

something like that

**Comment by nikolasburk** [comment]
Hi @tabvn! My sincere apologies for the delay of responding to your issue - unfortunately I wasn't able to put in much maintenance effort into How To GraphQL over the past months. However, I have just started a major cleanup and am taking a look at all issues.

As the `graphql-js` tutorial has been updated recently, it seems your question might be out of date. Please let me know if you have any other questions and I'll get back ASAP 🙂
